spring:
  application:
    name: service-platform
  datasource:
    url: jdbc:mysql://localhost:3306/services_platform_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234567890@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: devolpex@gmail.com
    password: jqxpocbfpqtietqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081

cors:
  allowed-origin: http://localhost:4200
